### ISSUE TITLE
None of the keybindings work (on Linux)

### ISSUE THREAD

**Issue by akaihola** [dsedivec/obsidian-emacs#1]
While this plugin does disable some of the default keybindings (like Shift-up/down), none of the Emacs keybindings do anything on my system. I extracted [v1.0.0.tar.gz](/dsedivec/obsidian-emacs/archive/refs/tags/v1.0.0.tar.gz) into my vault's `.obsidian/plugins/` directory and enabled `Emacs Keymap / Version 1.0.0 / By Dale Sedivec / Emacs keymap for CodeMirror 6 in Obsidian.` in the settings.

I'm running Obsidian 1.6.7 on NixOS (from the NixOS repository), and it works otherwise fine – also other community plugins.

There's also an ongoing discussion [Emacs bindings in the editor](https://forum.obsidian.md/t/emacs-bindings-in-the-editor/734/27) about this on the Obsidian forum.

The [Emacs Text Editor](/Klojer/obsidian-emacs-text-editor/) plugin is otherwise a working alternative, but it won't repeat the cursor keys (Ctrl-F/B/N/P).

[Obsidian Emacs Bindings](/kaz8096/obsidian-emacs-bindings) seems like the most promising plugin for this purpose.

**Comment by dsedivec** [comment]
Oh, yup, this extension doesn't work at all.  It's been a long time, but I think I ran into [this bug described on the Obsidian forums](https://forum.obsidian.md/t/change-builtin-obsidian-hotkey-handling-precedence-to-allow-for-overriding-hardcoded-mappings-in-plugins/40797/4).

I didn't even remember publishing this repo.  I think I'll archive it.  I never use it.  Thanks for your research, and I saw your thread on the forums.  I actually installed https://github.com/licht1stein/obsidian.el, and when I want to do serious editing of my Obsidian notes I just use Emacs directly!

Sorry for the disappointment.
